/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uis_items;

import data.pojo.responses.DeviceTransactionResponse;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import org.joda.time.DateTime;
import utils.ConfigurationsUtils;
import utils.MessageBox;

/**
 *
 * @author pc
 */
public class TransitionReportUIItem extends javax.swing.JPanel {

    /**
     * Creates new form TransitionReportUIItem
     *
     * @param trans
     * @param showDelimeterLine
     */
    public TransitionReportUIItem(DeviceTransactionResponse trans, boolean showDelimeterLine) {

        initComponents();

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        centerRenderer.setHorizontalTextPosition(JLabel.CENTER);

        advancedTable1.setDefaultRenderer(Object.class, centerRenderer);

        JTableHeader tableHeader = advancedTable1.getTableHeader();
        tableHeader.setBackground(Color.GRAY.brighter());
        tableHeader.setForeground(Color.BLACK);
        tableHeader.setFont(new Font("Arial", Font.BOLD, 13));

        tableHeader.setPreferredSize(new Dimension(100, 35));
        try {
            lblUnitName.setText(ConfigurationsUtils.getUnitName());
        } catch (Exception ex) {
            lblUnitName.setText("--");
        }
        try {
            lblAmeenElohda.setText(ConfigurationsUtils.getSenderName());
        } catch (Exception ex) {
            lblAmeenElohda.setText("--");
        }

        try {
            lblReportTitle.setText("إيصال استلام عهدة من " + ConfigurationsUtils.getDepartmentName());
        } catch (Exception ex) {
            Logger.getLogger(TransitionReportUIItem.class.getName()).log(Level.SEVERE, null, ex);
            lblReportTitle.setText("إيصال استلام عهدة من ");
        }
        try {
            lblDepManager.setText(ConfigurationsUtils.getDepManagerName());
            lblDepManagerJob.setText(ConfigurationsUtils.getDepManagerJobTitle());

        } catch (Exception e) {
            MessageBox.showErrorMessage(e.getMessage());
        }

//        lblTodayDate.setText(trans.getTransitionTimestamp());
        String dateNow = DateTime.now().toString("yyyy/MM/dd");

        lblTodayDate.setText(dateNow);

        lblDepReceiver.setText(trans.getNewDepartment().getDepartmentName());
        lblReceiver.setText(trans.getReceiverName());

        advancedTable1.getMutableModel().setValueAt(trans.getDevice().getType().getTypeName() + "-" + trans.getDevice().getModel().getModelNameWithBrand(), 0, 3);
        advancedTable1.getMutableModel().setValueAt(trans.getTransitionTimestamp(), 0, 1);
        advancedTable1.getMutableModel().setValueAt(trans.getDevice().getSerialNumber(), 0, 2);
        lblDelLine.setVisible(showDelimeterLine);
    }

    public void setManagerName(String name) {
        lblDepManager.setText(name);
    }

    public void setDepManagerJob(String job) {
        lblDepManagerJob.setText(job);
    }

    public void setReciverJobTitle(String job) {
        if (job.isEmpty()) {
            lblReceiverJobTitle.setText("وظيفة المستلم");
            lblReceiverJobTitle.setForeground(Color.RED.darker());
        } else {
            lblReceiverJobTitle.setText(job);
            lblReceiverJobTitle.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTodayDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUnitName = new javax.swing.JLabel();
        lblDepReceiver = new javax.swing.JLabel();
        lblReportTitle = new javax.swing.JLabel();
        lblDelLine = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        advancedTable1 = new base.AdvancedTable();
        jPanel1 = new javax.swing.JPanel();
        lblDepManager = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblDepManagerJob = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAmeenElohda = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblReceiver = new javax.swing.JLabel();
        lblReceiverJobTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("وزارة الدفاع");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        lblTodayDate.setText("2022/11/11");
        add(lblTodayDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setText("إلي فرع / قسم  :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        lblUnitName.setText("كلية الضباط الاحتياط");
        add(lblUnitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        lblDepReceiver.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblDepReceiver.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(lblDepReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 120, 300, -1));

        lblReportTitle.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblReportTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportTitle.setText("إيصال استلام عهدة من فرع النظم");
        add(lblReportTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 570, -1));

        lblDelLine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDelLine.setText("ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ");
        add(lblDelLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        advancedTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "1", null, "أحمد محمد حسان"}
            },
            new String [] {
                "ملاحظات", "تاريخ النقل", "السيريال", "اسم الصنف"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        advancedTable1.setAutoscrolls(false);
        advancedTable1.setFocusable(false);
        advancedTable1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        advancedTable1.setGridColor(new java.awt.Color(102, 102, 102));
        advancedTable1.setMinimumSize(new java.awt.Dimension(60, 45));
        advancedTable1.setPreferredScrollableViewportSize(new java.awt.Dimension(450, 500));
        advancedTable1.setRowHeight(40);
        advancedTable1.setRowMargin(10);
        advancedTable1.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(advancedTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 580, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDepManager.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblDepManager.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDepManager.setText("مقدم / حسام البسيوني علي عامر");
        jPanel1.add(lblDepManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 15));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("التوقيع (                                 )");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        lblDepManagerJob.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblDepManagerJob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDepManagerJob.setText("رئيس الفرع");
        jPanel1.add(lblDepManagerJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, 200, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAmeenElohda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblAmeenElohda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAmeenElohda.setText("مساعد / محمود محمد عبدالواحد");
        jPanel3.add(lblAmeenElohda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 140, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("المسلم");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 11, 150, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("التوقيع (                                 )");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("أميــن العهــدة");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 150, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("التوقيع (                                 )");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("المستلم");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 11, 150, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("رقم عسكري / ");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 20));

        lblReceiver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblReceiver.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReceiver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(lblReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 20));

        lblReceiverJobTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblReceiverJobTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblReceiverJobTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReceiverJobTitle.setText("وظيفة المستلم");
        lblReceiverJobTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblReceiverJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 150, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 242, -1, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private base.AdvancedTable advancedTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmeenElohda;
    private javax.swing.JLabel lblDelLine;
    private javax.swing.JLabel lblDepManager;
    private javax.swing.JLabel lblDepManagerJob;
    private javax.swing.JLabel lblDepReceiver;
    private javax.swing.JLabel lblReceiver;
    private javax.swing.JLabel lblReceiverJobTitle;
    private javax.swing.JLabel lblReportTitle;
    private javax.swing.JLabel lblTodayDate;
    private javax.swing.JLabel lblUnitName;
    // End of variables declaration//GEN-END:variables
}
