/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.departments;

import base.AdvancedFrame;
import data.pojo.Department;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repository.DepartmentsRepository;
import ui.devices.DevicesUI;
import utils.MessageBox;

/**
 *
 * @author pc
 */
public class DepartmentsUI extends AdvancedFrame {

    private final ArrayList<Department> allDepartments = new ArrayList<>();

    private static DepartmentsUI instance = null;

    /**
     * Creates new form DepartmentsUI
     */
    private DepartmentsUI() {
        initComponents();
    }

    public static DepartmentsUI getInstance() {

        synchronized (DepartmentsUI.class) {
            if (instance == null) {
                synchronized (DepartmentsUI.class) {
                    instance = new DepartmentsUI();
                }
            }

        }

        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDeps = new base.AdvancedTable();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAddDepartment = new javax.swing.JTextField();
        btnAddDepartment = new com.k33ptoo.components.KButton();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        lblDepId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSaveChanges = new com.k33ptoo.components.KButton();
        txtDepNameForUpdate = new javax.swing.JTextField();
        lblDeleteDep = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        kGradientPanel3.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 153, 153));

        tableDeps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم الفرع", "الاسم", "عدد الاجهزة", "عدد الأفرع التابعة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDeps.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableDeps.getTableHeader().setReorderingAllowed(false);
        tableDeps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDepsMouseClicked(evt);
            }
        });
        tableDeps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableDepsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableDeps);
        if (tableDeps.getColumnModel().getColumnCount() > 0) {
            tableDeps.getColumnModel().getColumn(0).setMinWidth(70);
            tableDeps.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableDeps.getColumnModel().getColumn(0).setMaxWidth(70);
            tableDeps.getColumnModel().getColumn(1).setResizable(false);
            tableDeps.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("افرع الكلية");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "إضافة فرع", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("اسم الفرع");

        txtAddDepartment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddDepartment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAddDepartment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddDepartmentKeyPressed(evt);
            }
        });

        btnAddDepartment.setText("إضافة الفرع");
        btnAddDepartment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddDepartment.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        btnAddDepartment.setkEndColor(new java.awt.Color(0, 102, 153));
        btnAddDepartment.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAddDepartment.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(txtAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "تعديل بيانات الفرع", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        kGradientPanel2.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 204, 204));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("رقم الفرع");

        lblDepId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDepId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("الاسم");

        btnSaveChanges.setText("حفظ التغييرات");
        btnSaveChanges.setFocusable(false);
        btnSaveChanges.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSaveChanges.setkBackGroundColor(new java.awt.Color(51, 51, 255));
        btnSaveChanges.setkEndColor(new java.awt.Color(51, 51, 255));
        btnSaveChanges.setkStartColor(new java.awt.Color(0, 102, 102));
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        txtDepNameForUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDepNameForUpdate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDepNameForUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDepNameForUpdateKeyPressed(evt);
            }
        });

        lblDeleteDep.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDeleteDep.setForeground(new java.awt.Color(255, 51, 51));
        lblDeleteDep.setText("حذف الفرع");
        lblDeleteDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDeleteDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteDepMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepNameForUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDeleteDep)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDepId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDepNameForUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeleteDep))
                .addContainerGap())
        );

        btnSaveChanges.setVisible(false);
        lblDeleteDep.setVisible(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getFormData();
    }//GEN-LAST:event_formWindowOpened

    private void tableDepsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDepsMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (evt.getClickCount() == 1) {
                int selectedRowIndex = tableDeps.getSelectedRow();
                Department dep = getDepartmentFromSelectedRow(selectedRowIndex);
                showItemDetails(dep);
                changeUpdateDepControllesVisibility();
            } else if (evt.getClickCount() == 2) {
                int selectedRowIndex = tableDeps.getSelectedRow();
                Department dep = getDepartmentFromSelectedRow(selectedRowIndex);
                startNewFrameWithOldFrame(DevicesUI.getInstance(dep.getDepartmentName(),-1,-1));
            }
        }
    }//GEN-LAST:event_tableDepsMouseClicked

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
        String department = txtAddDepartment.getText().trim();
        if (department.isEmpty()) {
            MessageBox.showErrorMessage("يرجي كتابة اسم الفرع");
            return;
        }

        boolean isAdded = addDepartmentToDB(department);
        if (isAdded) {
            getFormData();
        }
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void lblDeleteDepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteDepMouseClicked

        int selectedIndex = tableDeps.getSelectedRow();
        Department department = allDepartments.get(selectedIndex);
        
        int delOption = JOptionPane.showConfirmDialog(this, "سيتم حذف الفرع "+department.getDepartmentName()+"  نهائيا\nهل تريد المتابعة", "حذف الفرع", JOptionPane.YES_NO_OPTION);
        if (delOption == JOptionPane.YES_OPTION) {

            if (selectedIndex == -1) {
                MessageBox.showErrorMessage("يرجي اختيار فرع أولا للحذف");
                return;
            }

            boolean isDeleted = deleteDepartment(department);
            if (isDeleted) {
                lblDepId.setText("");
                txtDepNameForUpdate.setText("");
                tableDeps.setSelectionModel(new DefaultListSelectionModel());
                getFormData();
            }
        }

    }//GEN-LAST:event_lblDeleteDepMouseClicked

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed

        String depName = txtDepNameForUpdate.getText().trim();
        int selectedIndex = tableDeps.getSelectedRow();

        if (selectedIndex == -1) {
            MessageBox.showErrorMessage("يرجي اختيار فرع أولا لإكمال التعديل");
            return;
        }

        if (depName.isEmpty()) {
            MessageBox.showErrorMessage("يرجي كتابة اسم الفرع");
            return;
        }

        Department dep = allDepartments.get(selectedIndex);
        dep.setDepartmentName(depName);
        boolean isUpdated = updateDepartmet(dep);
        if (isUpdated) {

            getFormData();
        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void tableDepsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableDepsKeyPressed

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_F5:
                getFormData();
                break;
            case KeyEvent.VK_DELETE:
                lblDeleteDepMouseClicked(null);
                break;
            default:

        }


    }//GEN-LAST:event_tableDepsKeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        getFormData();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtAddDepartmentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddDepartmentKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAddDepartment.doClick();
        }
    }//GEN-LAST:event_txtAddDepartmentKeyPressed

    private void txtDepNameForUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepNameForUpdateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSaveChanges.doClick();
        }
    }//GEN-LAST:event_txtDepNameForUpdateKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        destroyInstance();
    }//GEN-LAST:event_formWindowClosed
    @Override
    public void destroyInstance() {
        allDepartments.clear();
        instance = null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAddDepartment;
    private com.k33ptoo.components.KButton btnSaveChanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lblDeleteDep;
    private javax.swing.JLabel lblDepId;
    private base.AdvancedTable tableDeps;
    private javax.swing.JTextField txtAddDepartment;
    private javax.swing.JTextField txtDepNameForUpdate;
    // End of variables declaration//GEN-END:variables

    private void getFormData() {
        ArrayList<Department> deps = getAllDepartments();
        if (deps != null) {
            allDepartments.clear();
            allDepartments.addAll(deps);

            fillDepartmentsTable(allDepartments);
        }

        lblDepId.setText("");
        txtAddDepartment.setText("");
        txtDepNameForUpdate.setText("");
        tableDeps.setSelectionModel(new DefaultListSelectionModel());

    }

    private ArrayList<Department> getAllDepartments() {
//        return DepartmentsRepository.getInstance().getAllDepartments();
        return DepartmentsRepository.getInstance().getAllLocalDepartments();
    }

    private void fillDepartmentsTable(ArrayList<Department> deps) {
        tableDeps.clearTable();
        DefaultTableModel model = tableDeps.getMutableModel();
//        System.out.println("DEps size is "+deps.size());

        deps.forEach((dep) -> {
            model.addRow(new Object[]{
                dep.getDepartmentId(),
                dep.getDepartmentName(),
                dep.getDevicesCountInDepartment()
            });
        });
        tableDeps.setModel(model);
    }

    private Department getDepartmentFromSelectedRow(int selectedRowIndex) {
        return allDepartments.get(selectedRowIndex);
    }

    private void showItemDetails(Department dep) {
        lblDepId.setText(dep.getDepartmentId() + "");
        txtDepNameForUpdate.setText(dep.getDepartmentName());
    }

    private void changeUpdateDepControllesVisibility() {
        btnSaveChanges.setVisible(true);
        lblDeleteDep.setVisible(true);
    }

    private boolean addDepartmentToDB(String department) {
//        return DepartmentsRepository.getInstance().addNewDepartment(department);
        return DepartmentsRepository.getInstance().addNewLocalDepartment(department);
    }

    private boolean deleteDepartment(Department department) {
//        return DepartmentsRepository.getInstance().deleteDepartment(department.getDepartmentId());
        return DepartmentsRepository.getInstance().deleteLocalDepartment(department.getDepartmentId());
    }

    private boolean updateDepartmet(Department dep) {
//        return DepartmentsRepository.getInstance().updateDepartment(dep.getDepartmentId(), dep.getDepartmentName());
        return DepartmentsRepository.getInstance().updateLocalDepartment(dep.getDepartmentId(), dep.getDepartmentName());
    }
}
