/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.test_connection;

import base.AdvancedFrame;
import data.pojo.DeviceType;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import repository.ConnectionRepository;
import repository.TypesRepository;
import ui.statictes.StatisticsUI;
import utils.MessageBox;

/**
 *
 * @author pc
 */
public class TestConfigtationsUI extends AdvancedFrame {

    private TestConnectionController splashContrpller = new TestConnectionController(
            ConnectionRepository.getInstance(), TypesRepository.getInstance()
    );

    /**
     * Creates new form TestConfigtations
     */
    public TestConfigtationsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainUi = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblSplashImage = new javax.swing.JLabel();
        btnCheckConnection = new com.k33ptoo.components.KButton();
        lblUnitName = new javax.swing.JLabel();
        lblDepName = new javax.swing.JLabel();
        jPanel1 = jPanel1 = new uis_items.AboutDevFooter().aboutDev;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("تطبيق مراقبة العهدة");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblAppName.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        lblAppName.setForeground(new java.awt.Color(51, 102, 255));
        lblAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppName.setText("تطبيق مراقبة العهدة");
        lblAppName.setToolTipText("");

        btnCheckConnection.setText("دخول ");
        btnCheckConnection.setFont(btnCheckConnection.getFont().deriveFont(btnCheckConnection.getFont().getStyle() | java.awt.Font.BOLD, btnCheckConnection.getFont().getSize()+4));
        btnCheckConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckConnectionActionPerformed(evt);
            }
        });

        lblUnitName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUnitName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUnitName.setText("كلية الضباط الإحتياط");

        lblDepName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDepName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDepName.setText("قسم نظم المعلومات");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainUiLayout = new javax.swing.GroupLayout(mainUi);
        mainUi.setLayout(mainUiLayout);
        mainUiLayout.setHorizontalGroup(
            mainUiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainUiLayout.createSequentialGroup()
                .addGroup(mainUiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainUiLayout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addGroup(mainUiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDepName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnitName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainUiLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lblSplashImage, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUiLayout.createSequentialGroup()
                        .addComponent(btnCheckConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUiLayout.createSequentialGroup()
                        .addComponent(lblAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(mainUiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUiLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        mainUiLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDepName, lblUnitName});

        mainUiLayout.setVerticalGroup(
            mainUiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainUiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUnitName)
                .addGap(6, 6, 6)
                .addComponent(lblDepName)
                .addGap(49, 49, 49)
                .addComponent(lblAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblSplashImage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCheckConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(mainUiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUiLayout.createSequentialGroup()
                    .addContainerGap(566, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainUi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainUi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckConnectionActionPerformed
//        try {
        /*
            boolean isConnected = new ConnectionRepository().checkConnection();
            if (isConnected) {
            startNewFrame(DevicesReportUI.getInstance());
            }else{
            int option = JOptionPane.showConfirmDialog(this, "هل تريد تشغيل برنامج السيرفر ؟","تشغيل السيرفر",JOptionPane.YES_OPTION);
            if (option == JOptionPane.YES_OPTION) {
            openXampControl();
            }
            }*/

//            mainUi.setVisible(false);
//            jDialog1.setVisible(true);
        splashContrpller.testConnection()
                .observe((Boolean isConnected) -> {
//                        mainUi.setVisible(true);
//                        jDialog1.dispose();
//                    System.out.println("isConnected => " + isConnected);
                    if (isConnected) {
                        ArrayList<DeviceType> allTypes = splashContrpller.getAllLocalTypes();
                        /*
                        try {
                           
//                        startNewFrame(DevicesReportUI.getInstance());


String endDateStr = ConfigurationsUtils.getEndDate();
System.out.println("End in => " + endDateStr);

SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
Date endDate = formatter.parse(endDateStr);

DateTime endArmyPeriod = new DateTime(endDate);
int days = Days.daysBetween(DateTime.now(), endArmyPeriod).getDays();
boolean appTraiEnded = DateTime.now().isAfter(endArmyPeriod);
if (appTraiEnded) {
MessageBox.showErrorMessage("لقد تم انتهاء فترة العمل المجانية\nنرجو ان نكون قد افدناكم");

lblHelpText.setVisible(true);
lblHelp2.setVisible(true);
btnActiveApp.setVisible(true);


}
System.out.println("Will End After => "+days + " Day ");
                        } catch (Exception e) {
                            MessageBox.showErrorMessage(e.getMessage());
                        }
                         */
                        startNewFrame(new StatisticsUI(allTypes));
                    } else {

                        /*int option = JOptionPane.showConfirmDialog(this, "هل تريد تشغيل برنامج السيرفر ؟", "تشغيل السيرفر", JOptionPane.YES_OPTION);
                        if (option == JOptionPane.YES_OPTION) {
                        openXampControl();
                        }*/
                    }

                });

//        } catch (Exception ex) {
//            Logger.getLogger(TestConfigtationsUI.class.getName()).log(Level.SEVERE, null, ex);
//            MessageBox.showErrorMessage(ex.getMessage());
//        }
    }//GEN-LAST:event_btnCheckConnectionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        progress.setVisible(false);

//        Config config = splashContrpller.getConfiObject();
        splashContrpller.setSplashScreenData(lblSplashImage, lblUnitName, lblDepName, lblAppName);
        setTitle(lblAppName.getText());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//        splashContrpller.destroy();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestConfigtationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestConfigtationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestConfigtationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestConfigtationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestConfigtationsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnCheckConnection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblDepName;
    private javax.swing.JLabel lblSplashImage;
    private javax.swing.JLabel lblUnitName;
    private javax.swing.JPanel mainUi;
    // End of variables declaration//GEN-END:variables

    private void openXampControl() {
        try {
            // TODO code application logic here
//            Desktop.getDesktop().browse(new URI("C://xampp/xampp_start.exe"));
//            Desktop.getDesktop().browse(new URI("C://xampp/mysql_start.bat"));
            Desktop.getDesktop().browse(new URI("C://xampp/xampp-control.exe"));

        } catch (URISyntaxException | IOException ex) {
            System.out.println("" + ex);
            String error = ex.getMessage();
            if (error.contains("cannot find the file")) {
                MessageBox.showErrorMessage("غير قادر علي تشغيل السيرفر\nتأكد من المسار" + "\n");
            } else if (error.contains("operation was canceled by the user")) {
                MessageBox.showErrorMessage("تم إلغاء فتح الملف" + "\n");
            } else {
                MessageBox.showErrorMessage(error);
            }

            System.exit(0);
        }
    }

    @Override
    public void destroyInstance() {
        splashContrpller.destroy();
        splashContrpller = null;
    }
}
