/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.statictes;

import base.AdvancedFrame;
import data.pojo.DashboardStaticsItem;
import data.pojo.DeviceType;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import ui.devices.DevicesUI;
import ui.reports.DevicesReportUI;
import uis_items.ItemDashboard;

/**
 *
 * @author pc
 */
public class StatisticsUI extends AdvancedFrame {

    /**
     * Creates new form StatisticsUI
     */
//    ArrayList<String> titles = new ArrayList<>();
//    ArrayList<String> images = new ArrayList<>();
//    ArrayList<String> counts = new ArrayList<>();
    private final ArrayList<DeviceType> devicesTypes = new ArrayList<>();

    public StatisticsUI(ArrayList<DeviceType> devices) {
        if (devices == null) {
            dispose();
            return;
        }

        this.devicesTypes.clear();
        this.devicesTypes.addAll(devices);

//        setSize(ScreenUtils.getScreenSize());
//        System.out.println(""+ScreenUtils.getScreenSize());
//        getWindows()[0].setMaximumSize(ScreenUtils.getScreenSize());
//        System.out.println("" + );
//        System.out.println("" + getWindows().length);
        initComponents();

        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        showStatistics();
//        fillArrays();
    }

    /*private void fillArrays() {
    titles.add("كمبيوتر");
    titles.add("حاسب آلي");
    titles.add("طابعة");
    titles.add("سكانر");
    titles.add("لابتوب");
    titles.add("طابعة");
    titles.add("سكانر");
    titles.add("لابتوب");
    titles.add("2لابتوب");
    
    
    images.add("http://localhost/DevicesManagement/uploads/images/image.png");
    images.add("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot (1).png");
    images.add("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot (1).png");
    images.add("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot (1).png");
    images.add("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot (1).png");
    images.add("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot (1).png");
    images.add("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot (1).png");
    images.add("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot (1).png");
    images.add("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot (1).png");
    images.add("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot (1).png");
    
    counts.add("25");
    counts.add("30");
    counts.add("35");
    counts.add("40");
    counts.add("45");
    counts.add("50");
    counts.add("40");
    counts.add("45");
    counts.add("50");
    //        counts.add("50");
    
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnShowReportsPage = new com.k33ptoo.components.KButton();
        lblDashboardTitle = new javax.swing.JLabel();
        lblStaticsTAG = new javax.swing.JLabel();
        lblNoItemsFounded = new javax.swing.JLabel();
        scrollPaneRecView = new javax.swing.JScrollPane();
        recView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("إحصائيات");
        setMinimumSize(new java.awt.Dimension(2828, 1391));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnShowReportsPage.setText("التقارير");
        btnShowReportsPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowReportsPageActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowReportsPage, new java.awt.GridBagConstraints());

        lblDashboardTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDashboardTitle.setForeground(new java.awt.Color(0, 102, 255));
        lblDashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboardTitle.setText("Dashboard ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(lblDashboardTitle, gridBagConstraints);

        lblStaticsTAG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStaticsTAG.setForeground(new java.awt.Color(0, 102, 255));
        lblStaticsTAG.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStaticsTAG.setText("احصائيات الأنواع");
        lblStaticsTAG.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 205, 0, 0);
        getContentPane().add(lblStaticsTAG, gridBagConstraints);

        lblNoItemsFounded.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNoItemsFounded.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoItemsFounded.setText("لا توجد أي بيانات حاليا قم بإضافة بيانات لتظهر هنا");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        getContentPane().add(lblNoItemsFounded, gridBagConstraints);

        recView.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        javax.swing.GroupLayout recViewLayout = new javax.swing.GroupLayout(recView);
        recView.setLayout(recViewLayout);
        recViewLayout.setHorizontalGroup(
            recViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2273, Short.MAX_VALUE)
        );
        recViewLayout.setVerticalGroup(
            recViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        scrollPaneRecView.setViewportView(recView);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1025;
        gridBagConstraints.ipady = 572;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 11, 10);
        getContentPane().add(scrollPaneRecView, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowReportsPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowReportsPageActionPerformed

        startNewFrame(DevicesReportUI.getInstance(), true);
    }//GEN-LAST:event_btnShowReportsPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsUI(new ArrayList<>()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnShowReportsPage;
    private javax.swing.JLabel lblDashboardTitle;
    private javax.swing.JLabel lblNoItemsFounded;
    private javax.swing.JLabel lblStaticsTAG;
    private javax.swing.JPanel recView;
    private javax.swing.JScrollPane scrollPaneRecView;
    // End of variables declaration//GEN-END:variables

    private void showStatistics() {

        recView.setVisible(!devicesTypes.isEmpty());
        lblNoItemsFounded.setVisible(devicesTypes.isEmpty());

        devicesTypes.forEach((type) -> {
            int rows = 0;
            int cols = 3;
            int marginVertical = 50;
            int marginHorozintal = 20;
            recView.setLayout(new java.awt.GridLayout(rows, cols, marginVertical, marginHorozintal));
//        ItemDashboard itemDashboard = new ItemDashboard();

            try {

//                Component itemPanel = new ItemDashboard().getDashboardItemView(new DashboardStaticsItem(type.getTypeName(), "http://localhost/DevicesManagement/uploads/images/image.png",type.getDevicesCountInType()+""));
                ItemDashboard dashboaedItem = new ItemDashboard();
                Component itemPanel = dashboaedItem.getDashboardItemView(new DashboardStaticsItem(type.getTypeName(), "", type.getDevicesCountInType() + ""));
//                System.out.println("Item Shown "+type.getTypeName());
                dashboaedItem.setOnItemClickListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent me) {
//                        int typeId = type.getTypeId();
                        startNewFrameWithOldFrame(DevicesUI.getInstance(
                                null,
                                type.getTypeId(),
                                -1)
                        );
                    }

                });
                recView.add(itemPanel);
//                System.out.println("Panel Added !");
//                pack();
            } catch (Exception ex) {
                Logger.getLogger(StatisticsUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        });

        pack();
    }

    @Override
    public void destroyInstance() {
        this.devicesTypes.clear();
        

    }

}
