/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.update_device_info;

import base.AdvancedFrame;
import data.pojo.Device;
import repository.DepartmentsRepository;
import repository.DevicesRepository;
import repository.ModelsRepository;
import repository.TypesRepository;
import ui.models_ui.ModelsUI;
import utils.MessageBox;

/**
 *
 * @author pc
 */
public class UpdateDeviceInfoUI extends AdvancedFrame {

    private  static UpdateDeviceInfoUI instance = null;
    private final UpdateDeviceController addDeviceController = new UpdateDeviceController(
            DevicesRepository.getInstance(),
            ModelsRepository.getInstance(),
            DepartmentsRepository.getInstance(),
            TypesRepository.getInstance()
    
    );
    
    private Device device =null;

    /**
     * Creates new form UpdateDeviceInfoUI
     *
     * @param _device
     * @return
     */
    public static UpdateDeviceInfoUI getInstance(Device _device) {

        synchronized (UpdateDeviceInfoUI.class) {
            if (instance == null) {
                synchronized(UpdateDeviceInfoUI.class){
                    instance = new UpdateDeviceInfoUI();
                }
            }
            
        }
        instance.device = _device;

        return instance;
    }

    private UpdateDeviceInfoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDeviceId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboModels = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDeviceName = new javax.swing.JTextField();
        btnUpdateInfo = new com.k33ptoo.components.KButton();
        lblAddNewDep1 = new javax.swing.JLabel();
        lblRefreshPage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("تحديث بيانات الجهاز");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kGradientPanel1.setkEndColor(java.awt.SystemColor.activeCaption);
        kGradientPanel1.setkGradientFocus(100);
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+1));
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("id");

        txtDeviceId.setEditable(false);
        txtDeviceId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDeviceId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()+1));
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("الموديل");

        comboModels.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+1));
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("الاسم");

        txtDeviceName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDeviceName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnUpdateInfo.setText("تعديل ابيانات");
        btnUpdateInfo.setFont(btnUpdateInfo.getFont().deriveFont(btnUpdateInfo.getFont().getStyle() | java.awt.Font.BOLD, btnUpdateInfo.getFont().getSize()+1));
        btnUpdateInfo.setkAllowGradient(false);
        btnUpdateInfo.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        btnUpdateInfo.setkBorderRadius(40);
        btnUpdateInfo.setkEndColor(new java.awt.Color(0, 102, 153));
        btnUpdateInfo.setkHoverColor(new java.awt.Color(0, 102, 153));
        btnUpdateInfo.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdateInfo.setkHoverStartColor(new java.awt.Color(0, 102, 153));
        btnUpdateInfo.setkPressedColor(new java.awt.Color(0, 102, 204));
        btnUpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInfoActionPerformed(evt);
            }
        });

        lblAddNewDep1.setFont(lblAddNewDep1.getFont().deriveFont(lblAddNewDep1.getFont().getStyle() | java.awt.Font.BOLD));
        lblAddNewDep1.setForeground(new java.awt.Color(51, 102, 255));
        lblAddNewDep1.setText("إضافة موديل جديد");
        lblAddNewDep1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddNewDep1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddNewDep1MouseClicked(evt);
            }
        });

        lblRefreshPage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRefreshPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefreshPage.setText("تحديث الصفحة");
        lblRefreshPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRefreshPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRefreshPageMouseClicked(evt);
            }
        });

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+1));
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("السيريال");

        txtSerialNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSerialNo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeviceName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeviceId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblAddNewDep1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboModels, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblRefreshPage)
                .addGap(337, 337, 337))
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboModels, txtDeviceId, txtDeviceName, txtSerialNo});

        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRefreshPage)
                .addGap(36, 36, 36)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboModels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAddNewDep1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnUpdateInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        lblRefreshPage.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInfoActionPerformed
        try {
            boolean isUpdated = addDeviceController.updateDeviceInfo(txtDeviceId,
                    txtSerialNo,
                    txtDeviceName,
                    device.getCurrentDepartment(),
                    comboModels
            );
            
            if (isUpdated) {
                dispose();
            }
        } catch (Exception ex) {
            MessageBox.showErrorMessage(ex.getMessage());
        }
    }//GEN-LAST:event_btnUpdateInfoActionPerformed

    private void lblAddNewDep1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewDep1MouseClicked
        startNewFrameWithOldFrame(ModelsUI.getInstance());
    }//GEN-LAST:event_lblAddNewDep1MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        addDeviceController.destroy();
        destroyInstance();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getFormData();
        putDeviceInfoInFields(device);
    }//GEN-LAST:event_formWindowOpened

    private void lblRefreshPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshPageMouseClicked
        refreshPage();
    }//GEN-LAST:event_lblRefreshPageMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//       putDeviceInfoInFields(device);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDeviceInfoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UpdateDeviceInfoUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnUpdateInfo;
    private javax.swing.JComboBox<String> comboModels;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblAddNewDep1;
    private javax.swing.JLabel lblRefreshPage;
    private javax.swing.JTextField txtDeviceId;
    private javax.swing.JTextField txtDeviceName;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables

    private void getFormData() {
        addDeviceController.getAllDepartments();
//        addDeviceController.fillDepartmentsIn(comboDeps);

        addDeviceController.putModelsIn(comboModels);
//        putDeviceInfoInFields(device);
    }

    private void refreshPage() {
        getFormData();
    }

    @Override
    public void destroyInstance() {
        device = null;
        addDeviceController.destroy();
        
        instance = null;
    }

    private void putDeviceInfoInFields(Device selectedDevice) {
        if (selectedDevice == null) {
            MessageBox.showErrorMessage("يرجي اختيار جهاز أولا للتعديل");
            dispose();
            return;
        }
        txtDeviceId.setText(selectedDevice.getDeviceId()+"");
        txtSerialNo.setText(selectedDevice.getSerialNumber());
        txtDeviceName.setText(selectedDevice.getDeviceName());
//        comboDeps.setSelectedItem(selectedDevice.getCurrentDepartment().getDepartmentName());
        comboModels.setSelectedItem(selectedDevice.getModel().getModelNameWithBrand());
//        System.out.println("De "+selectedDevice.getModel().getModelNameWithBrand());
    }
}
