/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.types_uis;

import base.AdvancedFrame;
import data.pojo.DeviceType;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import repository.TypesRepository;
import utils.MessageBox;

/**
 *
 * @author pc
 */
public class TypesUI extends AdvancedFrame {

    private final ArrayList<data.pojo.DeviceType> allTypes = new ArrayList<>();
    private static TypesUI instance = null;

    /**
     * Creates new form DepartmentsUI
     */
    private TypesUI() {
        initComponents();
    }

    public static TypesUI getInstance() {

        synchronized (TypesUI.class) {
            if (instance == null) {
                synchronized (TypesUI.class) {
                    instance = new TypesUI();
                }
            }

        }

        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTypes = new base.AdvancedTable();
        lblTableTitle = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAddType = new javax.swing.JTextField();
        btnAddType = new com.k33ptoo.components.KButton();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        lbTypeId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSaveChanges = new com.k33ptoo.components.KButton();
        txtTypeNameForUpdate = new javax.swing.JTextField();
        lblDeleteBrand = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDevicesCount = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRefreshPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        kGradientPanel3.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 153, 153));

        tableTypes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "اسم النوع", "عدد أجهزة النوع"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTypes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableTypes.getTableHeader().setReorderingAllowed(false);
        tableTypes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTypesMouseClicked(evt);
            }
        });
        tableTypes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableTypesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableTypes);
        if (tableTypes.getColumnModel().getColumnCount() > 0) {
            tableTypes.getColumnModel().getColumn(0).setPreferredWidth(20);
            tableTypes.getColumnModel().getColumn(1).setPreferredWidth(150);
            tableTypes.getColumnModel().getColumn(2).setPreferredWidth(60);
        }

        lblTableTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTableTitle.setForeground(new java.awt.Color(51, 102, 255));
        lblTableTitle.setText("انواع الأجهزة");
        lblTableTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTableTitleMouseClicked(evt);
            }
        });

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "إضافة نوع جهاز", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("اسم النوع");

        txtAddType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddType.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAddType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddTypeKeyPressed(evt);
            }
        });

        btnAddType.setText("إضافة النوع");
        btnAddType.setFont(btnAddType.getFont().deriveFont(btnAddType.getFont().getStyle() | java.awt.Font.BOLD, btnAddType.getFont().getSize()+1));
        btnAddType.setkAllowGradient(false);
        btnAddType.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        btnAddType.setkBorderRadius(40);
        btnAddType.setkEndColor(new java.awt.Color(0, 102, 153));
        btnAddType.setkHoverColor(new java.awt.Color(0, 102, 153));
        btnAddType.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAddType.setkHoverStartColor(new java.awt.Color(0, 102, 153));
        btnAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(txtAddType, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddType, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnAddType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "تعديل بيانات النوع", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        kGradientPanel2.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 204, 204));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("رقم النوع");

        lbTypeId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTypeId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("الاسم");

        btnSaveChanges.setText("حفظ التغييرات");
        btnSaveChanges.setFocusable(false);
        btnSaveChanges.setFont(btnSaveChanges.getFont().deriveFont(btnSaveChanges.getFont().getStyle() | java.awt.Font.BOLD, btnSaveChanges.getFont().getSize()+1));
        btnSaveChanges.setkAllowGradient(false);
        btnSaveChanges.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        btnSaveChanges.setkBorderRadius(40);
        btnSaveChanges.setkEndColor(new java.awt.Color(51, 51, 255));
        btnSaveChanges.setkHoverColor(new java.awt.Color(0, 102, 153));
        btnSaveChanges.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSaveChanges.setkStartColor(new java.awt.Color(0, 102, 102));
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        txtTypeNameForUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTypeNameForUpdate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTypeNameForUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTypeNameForUpdateKeyPressed(evt);
            }
        });

        lblDeleteBrand.setFont(lblDeleteBrand.getFont().deriveFont(lblDeleteBrand.getFont().getStyle() | java.awt.Font.BOLD));
        lblDeleteBrand.setForeground(new java.awt.Color(255, 51, 51));
        lblDeleteBrand.setText("حذف النوع");
        lblDeleteBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDeleteBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteBrandMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("عدد الأجهزة");

        lblDevicesCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDevicesCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTypeId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTypeNameForUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDevicesCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblDeleteBrand)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel6});

        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbTypeId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDevicesCount, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTypeNameForUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeleteBrand))
                .addContainerGap())
        );

        btnSaveChanges.setVisible(false);
        lblDeleteBrand.setVisible(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblRefreshPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRefreshPage.setText("تحديث الصفحة");
        lblRefreshPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRefreshPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRefreshPageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addComponent(lblRefreshPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTableTitle)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTableTitle)
                            .addComponent(lblRefreshPage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getFormData();
    }//GEN-LAST:event_formWindowOpened

    private void tableTypesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTypesMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (evt.getClickCount() == 1) {
                int selectedRowIndex = tableTypes.getSelectedRow();
                data.pojo.DeviceType type = getTypeFromSelectedRow(selectedRowIndex);
                showItemDetails(type);
                changeUpdateTypeControllesVisibility(true);
            }
        }
    }//GEN-LAST:event_tableTypesMouseClicked

    private void btnAddTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTypeActionPerformed
        String type = txtAddType.getText().trim();
        if (type.isEmpty()) {
            MessageBox.showErrorMessage("يرجي كتابة اسم النوع");
            return;
        }

        boolean isAdded = addTypeToDB(type);
        if (isAdded) {
            getFormData();
//            insertTypeToTable(type);
        }
    }//GEN-LAST:event_btnAddTypeActionPerformed

    private void lblDeleteBrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteBrandMouseClicked

        int delOption = JOptionPane.showConfirmDialog(this, "سيتم حذف النوع  نهائيا\nهل تريد المتابعة", "حذف " + txtTypeNameForUpdate.getText(), JOptionPane.YES_NO_OPTION);
        if (delOption == JOptionPane.YES_OPTION) {
            int selectedIndex = tableTypes.getSelectedRow();
            if (selectedIndex == -1) {
                MessageBox.showErrorMessage("يرجي اختيار نوع أولا للحذف");
                return;
            }

            data.pojo.DeviceType type = allTypes.get(selectedIndex);
            boolean isDeleted = deleteType(type);
            if (isDeleted) {
                lbTypeId.setText("");
                txtTypeNameForUpdate.setText("");
                tableTypes.setSelectionModel(new DefaultListSelectionModel());
                getFormData();
            }
        }

    }//GEN-LAST:event_lblDeleteBrandMouseClicked

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed

        String typeName = txtTypeNameForUpdate.getText().trim();
        int selectedIndex = tableTypes.getSelectedRow();

        if (selectedIndex == -1) {
            MessageBox.showErrorMessage("يرجي اختيار نوع أولا لإكمال التعديل");
            return;
        }

        if (typeName.isEmpty()) {
            MessageBox.showErrorMessage("يرجي كتابة اسم النوع");
            return;
        }

        data.pojo.DeviceType type = allTypes.get(selectedIndex);
        type.setTypeName(typeName);
        boolean isUpdated = updateType(type);
        if (isUpdated) {
            getFormData();
        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void tableTypesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableTypesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            getFormData();
        }

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            lblDeleteBrandMouseClicked(null);
        }
    }//GEN-LAST:event_tableTypesKeyPressed

    private void lblTableTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTableTitleMouseClicked

    }//GEN-LAST:event_lblTableTitleMouseClicked

    private void txtAddTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddTypeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAddType.doClick();
        }
    }//GEN-LAST:event_txtAddTypeKeyPressed

    private void txtTypeNameForUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypeNameForUpdateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSaveChanges.doClick();
        }
    }//GEN-LAST:event_txtTypeNameForUpdateKeyPressed

    private void lblRefreshPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshPageMouseClicked
        getFormData();
    }//GEN-LAST:event_lblRefreshPageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TypesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TypesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TypesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TypesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TypesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAddType;
    private com.k33ptoo.components.KButton btnSaveChanges;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lbTypeId;
    private javax.swing.JLabel lblDeleteBrand;
    private javax.swing.JLabel lblDevicesCount;
    private javax.swing.JLabel lblRefreshPage;
    private javax.swing.JLabel lblTableTitle;
    private base.AdvancedTable tableTypes;
    private javax.swing.JTextField txtAddType;
    private javax.swing.JTextField txtTypeNameForUpdate;
    // End of variables declaration//GEN-END:variables

    private void getFormData() {
        ArrayList<DeviceType> types = getAllTypes();
        if (types != null) {
            allTypes.clear();
            allTypes.addAll(types);

            fillTypesTable(types);
        }

//        emptyFormFields(this);
        txtAddType.setText("");
        lbTypeId.setText("");
        txtTypeNameForUpdate.setText("");
        tableTypes.setSelectionModel(new DefaultListSelectionModel());

        changeUpdateTypeControllesVisibility(false);
    }

    private ArrayList<data.pojo.DeviceType> getAllTypes() {
//        return TypesRepository.getInstance().getAllTypes();
        return TypesRepository.getInstance().getAllLocalTypes();
    }

    private void fillTypesTable(ArrayList<data.pojo.DeviceType> types) {
        tableTypes.clearTable();
        DefaultTableModel model = tableTypes.getMutableModel();

        types.forEach((type) -> {
            model.addRow(new Object[]{
                type.getTypeId(),
                type.getTypeName(),
                type.getDevicesCountInType()
            });
        });
        tableTypes.setModel(model);
    }

    private data.pojo.DeviceType getTypeFromSelectedRow(int selectedRowIndex) {
        return allTypes.get(selectedRowIndex);
    }

    private void showItemDetails(data.pojo.DeviceType type) {
        lbTypeId.setText(type.getTypeId() + "");
        txtTypeNameForUpdate.setText(type.getTypeName());
        lblDevicesCount.setText(type.getDevicesCountInType() + "");
    }

    private void changeUpdateTypeControllesVisibility(boolean isVisible) {
        btnSaveChanges.setVisible(isVisible);
        lblDeleteBrand.setVisible(isVisible);
    }

    private boolean addTypeToDB(String type) {
//        return TypesRepository.getInstance().addNewType(type);
        return TypesRepository.getInstance().addNewLocalType(type);
    }

    private boolean deleteType(DeviceType type) {
//        return TypesRepository.getInstance().deleteType(type.getTypeId());
        return TypesRepository.getInstance().deleteLocalType(type.getTypeId());
    }

    private boolean updateType(DeviceType type) {
//        return TypesRepository.getInstance().updateType(type.getTypeId(), type.getTypeName());
        return TypesRepository.getInstance().updateLocalType(type.getTypeId(), type.getTypeName());
    }

    private void emptyFormFields(Container container) {
        for (Component comp : container.getComponents()) {
            if (comp instanceof JTextField) {
                ((JTextField) comp).setText("");
            } else if (comp instanceof JLabel) {

                ((JLabel) comp).setText("");
            } else if (comp instanceof Container) {
                emptyFormFields((Container) comp);
            }
        }
    }

    @Override
    public void destroyInstance() {
        allTypes.clear();
        instance = null;
    }
}
